kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: node:14
    commands:
      - node --version
      - npm --version

  - name: build
    image: plugins/docker
    settings:
      repo: thapapath/your-repo
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  branch:
    - main
