env:
  DRONE_RPC_SECRET: ikVZIDsTLftbBNGMhKOqJHEAunelzXYQ
  DRONE_SERVER_HOST: 192.168.49.2
  DRONE_SERVER_PROTO: http
  DRONE_GITHUB_CLIENT_ID: Ov23lim2gQEzGI7BurhN
  DRONE_GITHUB_CLIENT_SECRET: 6574310ce0b649f0196d55523e2be6b7564f9683

service:
  type: LoadBalancer